name: venv
channels:
  - conda-forge
  - pytorch

dependencies:
  - python>=3.6
  - pytorch>=1.4.0
  - torchvision>=0.5.0
  - opencv>=4.2.0
  - matplotlib>=3.2.1
  - pip:
    - kornia>=0.2.0
    - pytorch-lightning>=0.7.2
